---
- name: Setup User(s)
  import_role:
    name: grog.user

- name: Copy bash files
  copy:
    src: "{{ item.1 }}"
    dest: "/home/{{ item.0.name }}/{{ item.1 }}"
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    mode: 0444
  loop: "{{ [user_list, user_list_host, user_list_group] | flatten | product(['.bash_aliases', '.bash_exports', '.bash_profile', '.bashrc', '.inputrc']) | list }}"
